In [116]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pandas as pd

In [117]:
fn = "ageSex_byState.csv"

pd.read_csv(fn,skiprows=2).iloc[:13,:]

,Label (Grouping),Total population,Total population!!AGE,Total population!!AGE!!Under 5 years,Total population!!AGE!!5 to 9 years,Total population!!AGE!!10 to 14 years,Total population!!AGE!!15 to 19 years,Total population!!AGE!!20 to 24 years,Total population!!AGE!!25 to 29 years,Total population!!AGE!!30 to 34 years,...,Total population!!SELECTED AGE CATEGORIES!!75 years and over,Total population!!SUMMARY INDICATORS,Total population!!SUMMARY INDICATORS!!Median age (years),Total population!!SUMMARY INDICATORS!!Sex ratio (males per 100 females),Total population!!SUMMARY INDICATORS!!Age dependency ratio,Total population!!SUMMARY INDICATORS!!Old-age dependency ratio,Total population!!SUMMARY INDICATORS!!Child dependency ratio,Total population!!PERCENT ALLOCATED,Total population!!PERCENT ALLOCATED!!Sex,Total population!!PERCENT ALLOCATED!!Age
0,Alabama,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Total,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Estimate,"4,893,186",NaN,"293,932","294,776","315,204","321,308","323,960","334,650","307,217",...,"336,393",NaN,39.2,93.6,64.6,27.8,36.8,NaN,(X),(X)
3,Percent,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Estimate,(X),NaN,6.0%,6.0%,6.4%,6.6%,6.6%,6.8%,6.3%,...,6.9%,NaN,(X),(X),(X),(X),(X),NaN,0.1%,1.8%
5,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Estimate,"2,365,734",NaN,"149,579","150,937","160,287","162,291","163,665","167,179","149,890",...,"134,066",NaN,37.7,(X),(X),(X),(X),NaN,(X),(X)
7,Percent Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Estimate,(X),NaN,6.3%,6.4%,6.8%,6.9%,6.9%,7.1%,6.3%,...,5.7%,NaN,(X),(X),(X),(X),(X),NaN,(X),(X)
9,Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Estimate,"2,527,452",NaN,"144,353","143,839","154,917","159,017","160,295","167,471","157,327",...,"202,327",NaN,40.6,(X),(X),(X),(X),NaN,(X),(X)
11,Percent Female,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Estimate,(X),NaN,5.7%,5.7%,6.1%,6.3%,6.3%,6.6%,6.2%,...,8.0%,NaN,(X),(X),(X),(X),(X),NaN,(X),(X)

In [123]:
df = pd.read_csv("ageSex_byState.csv", skiprows=2, index_col = 0).transpose()
df

ParserError: Passed header=[0,1,2] are too many rows for this multi_index of columns

In [118]:
fns = ["ageSex_byState.csv", "economic_byState.csv", "healthInsurance_byState.csv",
      "poverty_byState.csv", "race_byState.csv"]

dfs = []
for file in fns:
    print(file)
    df = pd.read_csv(file, skiprows=2, index_col = 0)
    df = df.transpose()
    df.columns = [str(col).replace(u'\xa0', u'') for col in df.columns]
    dfs.append(df)
    print(df.columns)
    del df

dfs[0].head()

ageSex_byState.csv
Index(['Alabama', 'Total', 'Estimate', 'Percent', 'Estimate', 'Male',
       'Estimate', 'Percent Male', 'Estimate', 'Female',
       ...
       'Percent', 'Estimate', 'Male', 'Estimate', 'Percent Male', 'Estimate',
       'Female', 'Estimate', 'Percent Female', 'Estimate'],
      dtype='object', length=689)
economic_byState.csv
Index(['nan', 'nan', 'Label (Grouping)', 'Alabama', 'Estimate', 'Percent',
       'Alaska', 'Estimate', 'Percent', 'Arizona',
       ...
       'Percent', 'Wyoming', 'Estimate', 'Percent', 'Puerto Rico', 'Estimate',
       'Percent', 'United States', 'Estimate', 'Percent'],
      dtype='object', length=162)
healthInsurance_byState.csv
Index(['nan', 'Label (Grouping)', 'Alabama', 'Total', 'Estimate',
       'Margin of Error', 'Insured', 'Estimate', 'Margin of Error',
       'Percent Insured',
       ...
       'Margin of Error', 'Percent Insured', 'Estimate', 'Margin of Error',
       'Uninsured', 'Estimate', 'Margin of Error', 'Percent Uninsured',
       'Estimate', 'Margin of Error'],
      dtype='object', length=850)
poverty_byState.csv
Index(['nan', 'Label (Grouping)', 'Alabama', 'Total', 'Estimate',
       'Below poverty level', 'Estimate', 'Percent below poverty level',
       'Estimate', 'Alaska',
       ...
       'Estimate', 'Percent below poverty level', 'Estimate', 'United States',
       'Total', 'Estimate', 'Below poverty level', 'Estimate',
       'Percent below poverty level', 'Estimate'],
      dtype='object', length=373)
race_byState.csv
Index(['nan', 'Label (Grouping)', 'Alabama', 'Alabama', 'Alaska', 'Alaska',
       'Arizona', 'Arizona', 'Arkansas', 'Arkansas',
       ...
       'West Virginia', 'West Virginia', 'Wisconsin', 'Wisconsin', 'Wyoming',
       'Wyoming', 'Puerto Rico', 'Puerto Rico', 'United States',
       'United States'],
      dtype='object', length=108)

,Alabama,Total,Estimate,Percent,Estimate,Male,Estimate,Percent Male,Estimate,Female,...,Percent,Estimate,Male,Estimate,Percent Male,Estimate,Female,Estimate,Percent Female,Estimate
Total population,NaN,NaN,"4,893,186",NaN,(X),NaN,"2,365,734",NaN,(X),NaN,...,NaN,(X),NaN,"160,818,530",NaN,(X),NaN,"165,750,778",NaN,(X)
Total population!!AGE,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Total population!!AGE!!Under 5 years,NaN,NaN,"293,932",NaN,6.0%,NaN,"149,579",NaN,6.3%,NaN,...,NaN,6.0%,NaN,"10,051,876",NaN,6.3%,NaN,"9,598,316",NaN,5.8%
Total population!!AGE!!5 to 9 years,NaN,NaN,"294,776",NaN,6.0%,NaN,"150,937",NaN,6.4%,NaN,...,NaN,6.1%,NaN,"10,191,107",NaN,6.3%,NaN,"9,787,932",NaN,5.9%
Total population!!AGE!!10 to 14 years,NaN,NaN,"315,204",NaN,6.4%,NaN,"160,287",NaN,6.8%,NaN,...,NaN,6.5%,NaN,"10,797,748",NaN,6.7%,NaN,"10,310,162",NaN,6.2%

In [119]:
states = {
    'AK': 'Alaska',
    'AL': 'Alabama',
    'AR': 'Arkansas',
    'AZ': 'Arizona',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DC': 'District of Columbia',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'IA': 'Iowa',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'MA': 'Massachusetts',
    'MD': 'Maryland',
    'ME': 'Maine',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MO': 'Missouri',
    'MS': 'Mississippi',
    'MT': 'Montana',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'NE': 'Nebraska',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NV': 'Nevada',
    'NY': 'New York',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VA': 'Virginia',
    'VT': 'Vermont',
    'WA': 'Washington',
    'WI': 'Wisconsin',
    'WV': 'West Virginia',
    'WY': 'Wyoming',
    'PR': "Puerto Rico",
    'US': 'United States'
}
states = {y:x for x,y in states.items()}

In [120]:
def rename_cols(df):
    cols = df.columns
    indices = sorted([[i, name, states[name]] for i,name in enumerate(cols) if name in states.keys()])
    
    newcols = []
    for i in range(0, len(indices)):
        ### first, get the starting index + the state and abbreviation
        s_ind, st, abbv = indices[i][0], indices[i][1], indices[i][2]
        if (i+1) == len(indices):
            e_ind = df.shape[1]
        else:
            e_ind = indices[i+1][0]
        
        print(f'{s_ind}, {e_ind}')
        st_cols = cols[s_ind:e_ind]
        newcol_state = [abbv + "_" + col.replace(u'\xa0', u'') for col in st_cols]
        newcols.extend(newcol_state)
    df.columns = newcols
    return df

In [121]:
df_test = dfs[0].copy()
rename_cols(df_test), df_test.shape

0, 13
13, 26
26, 39
39, 52
52, 65
65, 78
78, 91
91, 104
104, 117
117, 130
130, 143
143, 156
156, 169
169, 182
182, 195
195, 208
208, 221
221, 234
234, 247
247, 260
260, 273
273, 286
286, 299
299, 312
312, 325
325, 338
338, 351
351, 364
364, 377
377, 390
390, 403
403, 416
416, 429
429, 442
442, 455
455, 468
468, 481
481, 494
494, 507
507, 520
520, 533
533, 546
546, 559
559, 572
572, 585
585, 598
598, 611
611, 624
624, 637
637, 650
650, 663
663, 676
676, 689

(                                                   AL_Alabama AL_Total  \
 Total population                                          NaN      NaN
 Total population!!AGE                                     NaN      NaN
 Total population!!AGE!!Under 5 years                      NaN      NaN
 Total population!!AGE!!5 to 9 years                       NaN      NaN
 Total population!!AGE!!10 to 14 years                     NaN      NaN
 Total population!!AGE!!15 to 19 years                     NaN      NaN
 Total population!!AGE!!20 to 24 years                     NaN      NaN
 Total population!!AGE!!25 to 29 years                     NaN      NaN
 Total population!!AGE!!30 to 34 years                     NaN      NaN
 Total population!!AGE!!35 to 39 years                     NaN      NaN
 Total population!!AGE!!40 to 44 years                     NaN      NaN
 Total population!!AGE!!45 to 49 years                     NaN      NaN
 Total population!!AGE!!50 to 54 years                     NaN      NaN
 Total population!!AGE!!55 to 59 years                     NaN      NaN
 Total population!!AGE!!60 to 64 years                     NaN      NaN
 Total population!!AGE!!65 to 69 years                     NaN      NaN
 Total population!!AGE!!70 to 74 years                     NaN      NaN
 Total population!!AGE!!75 to 79 years                     NaN      NaN
 Total population!!AGE!!80 to 84 years                     NaN      NaN
 Total population!!AGE!!85 years and over                  NaN      NaN
 Total population!!SELECTED AGE CATEGORIES                 NaN      NaN
 Total population!!SELECTED AGE CATEGORIES!!5 to...        NaN      NaN
 Total population!!SELECTED AGE CATEGORIES!!15 t...        NaN      NaN
 Total population!!SELECTED AGE CATEGORIES!!Unde...        NaN      NaN
 Total population!!SELECTED AGE CATEGORIES!!18 t...        NaN      NaN
 Total population!!SELECTED AGE CATEGORIES!!15 t...        NaN      NaN
 Total population!!SELECTED AGE CATEGORIES!!16 y...        NaN      NaN
 Total population!!SELECTED AGE CATEGORIES!!18 y...        NaN      NaN
 Total population!!SELECTED AGE CATEGORIES!!21 y...        NaN      NaN
 Total population!!SELECTED AGE CATEGORIES!!60 y...        NaN      NaN
 Total population!!SELECTED AGE CATEGORIES!!62 y...        NaN      NaN
 Total population!!SELECTED AGE CATEGORIES!!65 y...        NaN      NaN
 Total population!!SELECTED AGE CATEGORIES!!75 y...        NaN      NaN
 Total population!!SUMMARY INDICATORS                      NaN      NaN
 Total population!!SUMMARY INDICATORS!!Median ag...        NaN      NaN
 Total population!!SUMMARY INDICATORS!!Sex ratio...        NaN      NaN
 Total population!!SUMMARY INDICATORS!!Age depen...        NaN      NaN
 Total population!!SUMMARY INDICATORS!!Old-age d...        NaN      NaN
 Total population!!SUMMARY INDICATORS!!Child dep...        NaN      NaN
 Total population!!PERCENT ALLOCATED                       NaN      NaN
 Total population!!PERCENT ALLOCATED!!Sex                  NaN      NaN
 Total population!!PERCENT ALLOCATED!!Age                  NaN      NaN

                                                    AL_Estimate AL_Percent  \
 Total population                                     4,893,186        NaN
 Total population!!AGE                                      NaN        NaN
 Total population!!AGE!!Under 5 years                   293,932        NaN
 Total population!!AGE!!5 to 9 years                    294,776        NaN
 Total population!!AGE!!10 to 14 years                  315,204        NaN
 Total population!!AGE!!15 to 19 years                  321,308        NaN
 Total population!!AGE!!20 to 24 years                  323,960        NaN
 Total population!!AGE!!25 to 29 years                  334,650        NaN
 Total population!!AGE!!30 to 34 years                  307,217        NaN
 Total population!!AGE!!35 to 39 years                  301,404        NaN
 Total population!!AGE!!40 to 44 years                  293,852        NaN
 Total population!!AGE!!45 to 49 years                  308,836        NaN
 Total population!!AGE!!50 to 54 years                  316,996        NaN
 Total population!!AGE!!55 to 59 years                  331,903        NaN
 Total population!!AGE!!60 to 64 years                  321,714        NaN
 Total population!!AGE!!65 to 69 years                  273,648        NaN
 Total population!!AGE!!70 to 74 years                  217,393        NaN
 Total population!!AGE!!75 to 79 years                  145,827        NaN
 Total population!!AGE!!80 to 84 years                  101,941        NaN
 Total population!!AGE!!85 years and over                88,625        NaN
 Total population!!SELECTED AGE CATEGORIES                  NaN        NaN
 Total population!!SELECTED AGE CATEGORIES!!5 to...     609,980        NaN
 Total population!!SELECTED AGE CATEGORIES!!15 t...     189,000        NaN
 Total population!!SELECTED AGE CATEGORIES!!Unde...   1,092,912        NaN
 Total population!!SELECTED AGE CATEGORIES!!18 t...     456,268        NaN
 Total population!!SELECTED AGE CATEGORIES!!15 t...   1,882,391        NaN
 Total population!!SELECTED AGE CATEGORIES!!16 y...   3,926,842        NaN
 Total population!!SELECTED AGE CATEGORIES!!18 y...   3,800,274        NaN
 Total population!!SELECTED AGE CATEGORIES!!21 y...   3,595,726        NaN
 Total population!!SELECTED AGE CATEGORIES!!60 y...   1,149,148        NaN
 Total population!!SELECTED AGE CATEGORIES!!62 y...   1,016,937        NaN
 Total population!!SELECTED AGE CATEGORIES!!65 y...     827,434        NaN
 Total population!!SELECTED AGE CATEGORIES!!75 y...     336,393        NaN
 Total population!!SUMMARY INDICATORS                       NaN        NaN
 Total population!!SUMMARY INDICATORS!!Median ag...        39.2        NaN
 Total population!!SUMMARY INDICATORS!!Sex ratio...        93.6        NaN
 Total population!!SUMMARY INDICATORS!!Age depen...        64.6        NaN
 Total population!!SUMMARY INDICATORS!!Old-age d...        27.8        NaN
 Total population!!SUMMARY INDICATORS!!Child dep...        36.8        NaN
 Total population!!PERCENT ALLOCATED                        NaN        NaN
 Total population!!PERCENT ALLOCATED!!Sex                   (X)        NaN
 Total population!!PERCENT ALLOCATED!!Age                   (X)        NaN

                                                    AL_Estimate AL_Male  \
 Total population                                           (X)     NaN
 Total population!!AGE                                      NaN     NaN
 Total population!!AGE!!Under 5 years                      6.0%     NaN
 Total population!!AGE!!5 to 9 years                       6.0%     NaN
 Total population!!AGE!!10 to 14 years                     6.4%     NaN
 Total population!!AGE!!15 to 19 years                     6.6%     NaN
 Total population!!AGE!!20 to 24 years                     6.6%     NaN
 Total population!!AGE!!25 to 29 years                     6.8%     NaN
 Total population!!AGE!!30 to 34 years                     6.3%     NaN
 Total population!!AGE!!35 to 39 years                     6.2%     NaN
 Total population!!AGE!!40 to 44 years                     6.0%     NaN
 Total population!!AGE!!45 to 49 years                     6.3%     NaN
 Total population!!AGE!!50 to 54 years                     6.5%     NaN
 Total population!!AGE!!55 to 59 years                     6.8%     NaN
 Total population!!AGE!!60 to 64 years                     6.6%     NaN
 Total population!!AGE!!65 to 69 years                     5.6%     NaN
 Total population!!AGE!!70 to 74 years                     4.4%     NaN
 Total population!!AGE!!75 to 79 years                     3.0%     NaN
 Total population!!AGE!!80 to 84 years                     2.1%     NaN
 Total population!!AGE!!85 years and over                  1.8%     NaN
 Total population!!SELECTED AGE CATEGORIES                  NaN     NaN
 Total population!!SELECTED AGE CATEGORIES!!5 to...       12.5%     NaN
 Total population!!SELECTED AGE CATEGORIES!!15 t...        3.9%     NaN
 Total population!!SELECTED AGE CATEGORIES!!Unde...       22.3%     NaN
 Total population!!SELECTED AGE CATEGORIES!!18 t...        9.3%     NaN
 Total population!!SELECTED AGE CATEGORIES!!15 t...       38.5%     NaN
 Total population!!SELECTED AGE CATEGORIES!!16 y...       80.3%     NaN
 Total population!!SELECTED AGE CATEGORIES!!18 y...       77.7%     NaN
 Total population!!SELECTED AGE CATEGORIES!!21 y...       73.5%     NaN
 Total population!!SELECTED AGE CATEGORIES!!60 y...       23.5%     NaN
 Total population!!SELECTED AGE CATEGORIES!!62 y...       20.8%     NaN
 Total population!!SELECTED AGE CATEGORIES!!65 y...       16.9%     NaN
 Total population!!SELECTED AGE CATEGORIES!!75 y...        6.9%     NaN
 Total population!!SUMMARY INDICATORS                       NaN     NaN
 Total population!!SUMMARY INDICATORS!!Median ag...         (X)     NaN
 Total population!!SUMMARY INDICATORS!!Sex ratio...         (X)     NaN
 Total population!!SUMMARY INDICATORS!!Age depen...         (X)     NaN
 Total population!!SUMMARY INDICATORS!!Old-age d...         (X)     NaN
 Total population!!SUMMARY INDICATORS!!Child dep...         (X)     NaN
 Total population!!PERCENT ALLOCATED                        NaN     NaN
 Total population!!PERCENT ALLOCATED!!Sex                  0.1%     NaN
 Total population!!PERCENT ALLOCATED!!Age                  1.8%     NaN

                                                    AL_Estimate  \
 Total population                                     2,365,734
 Total population!!AGE                                      NaN
 Total population!!AGE!!Under 5 years                   149,579
 Total population!!AGE!!5 to 9 years                    150,937
 Total population!!AGE!!10 to 14 years                  160,287
 Total population!!AGE!!15 to 19 years                  162,291
 Total population!!AGE!!20 to 24 years                  163,665
 Total population!!AGE!!25 to 29 years                  167,179
 Total population!!AGE!!30 to 34 years                  149,890
 Total population!!AGE!!35 to 39 years                  144,863
 Total population!!AGE!!40 to 44 years                  142,671
 Total population!!AGE!!45 to 49 years                  149,680
 Total population!!AGE!!50 to 54 years                  153,533
 Total population!!AGE!!55 to 59 years                  158,953
 Total population!!AGE!!60 to 64 years                  151,998
 Total population!!AGE!!65 to 69 years                  127,425
 Total population!!AGE!!70 to 74 years                   98,717
 Total population!!AGE!!75 to 79 years                   63,852
 Total population!!AGE!!80 to 84 years                   41,156
 Total population!!AGE!!85 years and over                29,058
 Total population!!SELECTED AGE CATEGORIES                  NaN
 Total population!!SELECTED AGE CATEGORIES!!5 to...     311,224
 Total population!!SELECTED AGE CATEGORIES!!15 t...      96,832
 Total population!!SELECTED AGE CATEGORIES!!Unde...     557,635
 Total population!!SELECTED AGE CATEGORIES!!18 t...     229,124
 Total population!!SELECTED AGE CATEGORIES!!15 t...     930,559
 Total population!!SELECTED AGE CATEGORIES!!16 y...   1,873,092
 Total population!!SELECTED AGE CATEGORIES!!18 y...   1,808,099
 Total population!!SELECTED AGE CATEGORIES!!21 y...   1,705,935
 Total population!!SELECTED AGE CATEGORIES!!60 y...     512,206
 Total population!!SELECTED AGE CATEGORIES!!62 y...     450,474
 Total population!!SELECTED AGE CATEGORIES!!65 y...     360,208
 Total population!!SELECTED AGE CATEGORIES!!75 y...     134,066
 Total population!!SUMMARY INDICATORS                       NaN
 Total population!!SUMMARY INDICATORS!!Median ag...        37.7
 Total population!!SUMMARY INDICATORS!!Sex ratio...         (X)
 Total population!!SUMMARY INDICATORS!!Age depen...         (X)
 Total population!!SUMMARY INDICATORS!!Old-age d...         (X)
 Total population!!SUMMARY INDICATORS!!Child dep...         (X)
 Total population!!PERCENT ALLOCATED                        NaN
 Total population!!PERCENT ALLOCATED!!Sex                   (X)
 Total population!!PERCENT ALLOCATED!!Age                   (X)

                                                    AL_Percent Male  \
 Total population                                               NaN
 Total population!!AGE                                          NaN
 Total population!!AGE!!Under 5 years                           NaN
 Total population!!AGE!!5 to 9 years                            NaN
 Total population!!AGE!!10 to 14 years                          NaN
 Total population!!AGE!!15 to 19 years                          NaN
 Total population!!AGE!!20 to 24 years                          NaN
 Total population!!AGE!!25 to 29 years                          NaN
 Total population!!AGE!!30 to 34 years                          NaN
 Total population!!AGE!!35 to 39 years                          NaN
 Total population!!AGE!!40 to 44 years                          NaN
 Total population!!AGE!!45 to 49 years                          NaN
 Total population!!AGE!!50 to 54 years                          NaN
 Total population!!AGE!!55 to 59 years                          NaN
 Total population!!AGE!!60 to 64 years                          NaN
 Total population!!AGE!!65 to 69 years                          NaN
 Total population!!AGE!!70 to 74 years                          NaN
 Total population!!AGE!!75 to 79 years                          NaN
 Total population!!AGE!!80 to 84 years                          NaN
 Total population!!AGE!!85 years and over                       NaN
 Total population!!SELECTED AGE CATEGORIES                      NaN
 Total population!!SELECTED AGE CATEGORIES!!5 to...             NaN
 Total population!!SELECTED AGE CATEGORIES!!15 t...             NaN
 Total population!!SELECTED AGE CATEGORIES!!Unde...             NaN
 Total population!!SELECTED AGE CATEGORIES!!18 t...             NaN
 Total population!!SELECTED AGE CATEGORIES!!15 t...             NaN
 Total population!!SELECTED AGE CATEGORIES!!16 y...             NaN
 Total population!!SELECTED AGE CATEGORIES!!18 y...             NaN
 Total population!!SELECTED AGE CATEGORIES!!21 y...             NaN
 Total population!!SELECTED AGE CATEGORIES!!60 y...             NaN
 Total population!!SELECTED AGE CATEGORIES!!62 y...             NaN
 Total population!!SELECTED AGE CATEGORIES!!65 y...             NaN
 Total population!!SELECTED AGE CATEGORIES!!75 y...             NaN
 Total population!!SUMMARY INDICATORS                           NaN
 Total population!!SUMMARY INDICATORS!!Median ag...             NaN
 Total population!!SUMMARY INDICATORS!!Sex ratio...             NaN
 Total population!!SUMMARY INDICATORS!!Age depen...             NaN
 Total population!!SUMMARY INDICATORS!!Old-age d...             NaN
 Total population!!SUMMARY INDICATORS!!Child dep...             NaN
 Total population!!PERCENT ALLOCATED                            NaN
 Total population!!PERCENT ALLOCATED!!Sex                       NaN
 Total population!!PERCENT ALLOCATED!!Age                       NaN

                                                    AL_Estimate AL_Female  ...  \
 Total population                                           (X)       NaN  ...
 Total population!!AGE                                      NaN       NaN  ...
 Total population!!AGE!!Under 5 years                      6.3%       NaN  ...
 Total population!!AGE!!5 to 9 years                       6.4%       NaN  ...
 Total population!!AGE!!10 to 14 years                     6.8%       NaN  ...
 Total population!!AGE!!15 to 19 years                     6.9%       NaN  ...
 Total population!!AGE!!20 to 24 years                     6.9%       NaN  ...
 Total population!!AGE!!25 to 29 years                     7.1%       NaN  ...
 Total population!!AGE!!30 to 34 years                     6.3%       NaN  ...
 Total population!!AGE!!35 to 39 years                     6.1%       NaN  ...
 Total population!!AGE!!40 to 44 years                     6.0%       NaN  ...
 Total population!!AGE!!45 to 49 years                     6.3%       NaN  ...
 Total population!!AGE!!50 to 54 years                     6.5%       NaN  ...
 Total population!!AGE!!55 to 59 years                     6.7%       NaN  ...
 Total population!!AGE!!60 to 64 years                     6.4%       NaN  ...
 Total population!!AGE!!65 to 69 years                     5.4%       NaN  ...
 Total population!!AGE!!70 to 74 years                     4.2%       NaN  ...
 Total population!!AGE!!75 to 79 years                     2.7%       NaN  ...
 Total population!!AGE!!80 to 84 years                     1.7%       NaN  ...
 Total population!!AGE!!85 years and over                  1.2%       NaN  ...
 Total population!!SELECTED AGE CATEGORIES                  NaN       NaN  ...
 Total population!!SELECTED AGE CATEGORIES!!5 to...       13.2%       NaN  ...
 Total population!!SELECTED AGE CATEGORIES!!15 t...        4.1%       NaN  ...
 Total population!!SELECTED AGE CATEGORIES!!Unde...       23.6%       NaN  ...
 Total population!!SELECTED AGE CATEGORIES!!18 t...        9.7%       NaN  ...
 Total population!!SELECTED AGE CATEGORIES!!15 t...       39.3%       NaN  ...
 Total population!!SELECTED AGE CATEGORIES!!16 y...       79.2%       NaN  ...
 Total population!!SELECTED AGE CATEGORIES!!18 y...       76.4%       NaN  ...
 Total population!!SELECTED AGE CATEGORIES!!21 y...       72.1%       NaN  ...
 Total population!!SELECTED AGE CATEGORIES!!60 y...       21.7%       NaN  ...
 Total population!!SELECTED AGE CATEGORIES!!62 y...       19.0%       NaN  ...
 Total population!!SELECTED AGE CATEGORIES!!65 y...       15.2%       NaN  ...
 Total population!!SELECTED AGE CATEGORIES!!75 y...        5.7%       NaN  ...
 Total population!!SUMMARY INDICATORS                       NaN       NaN  ...
 Total population!!SUMMARY INDICATORS!!Median ag...         (X)       NaN  ...
 Total population!!SUMMARY INDICATORS!!Sex ratio...         (X)       NaN  ...
 Total population!!SUMMARY INDICATORS!!Age depen...         (X)       NaN  ...
 Total population!!SUMMARY INDICATORS!!Old-age d...         (X)       NaN  ...
 Total population!!SUMMARY INDICATORS!!Child dep...         (X)       NaN  ...
 Total population!!PERCENT ALLOCATED                        NaN       NaN  ...
 Total population!!PERCENT ALLOCATED!!Sex                   (X)       NaN  ...
 Total population!!PERCENT ALLOCATED!!Age                   (X)       NaN  ...

                                                    US_Percent US_Estimate  \
 Total population                                          NaN         (X)
 Total population!!AGE                                     NaN         NaN
 Total population!!AGE!!Under 5 years                      NaN        6.0%
 Total population!!AGE!!5 to 9 years                       NaN        6.1%
 Total population!!AGE!!10 to 14 years                     NaN        6.5%
 Total population!!AGE!!15 to 19 years                     NaN        6.5%
 Total population!!AGE!!20 to 24 years                     NaN        6.7%
 Total population!!AGE!!25 to 29 years                     NaN        7.1%
 Total population!!AGE!!30 to 34 years                     NaN        6.8%
 Total population!!AGE!!35 to 39 years                     NaN        6.5%
 Total population!!AGE!!40 to 44 years                     NaN        6.1%
 Total population!!AGE!!45 to 49 years                     NaN        6.3%
 Total population!!AGE!!50 to 54 years                     NaN        6.4%
 Total population!!AGE!!55 to 59 years                     NaN        6.7%
 Total population!!AGE!!60 to 64 years                     NaN        6.2%
 Total population!!AGE!!65 to 69 years                     NaN        5.3%
 Total population!!AGE!!70 to 74 years                     NaN        4.1%
 Total population!!AGE!!75 to 79 years                     NaN        2.8%